modLoader = "kotlinforforge"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Lizard-Of-Oz/Inventorio"
license = "GPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="https://github.com/Lizard-Of-Oz/Inventorio"

[[dependencies.inventorio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventorio]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventorio]]
modId = "cloth_config"
mandatory = true
versionRange = "[5,)"
ordering = "NONE"
side = "CLIENT"